// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://usnhwmbdbdmkoeonuhky.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVzbmh3bWJkYmRta29lb251aGt5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzOTkxNDEsImV4cCI6MjA1Nzk3NTE0MX0.r8T9SfEtxY_iYXvioXL-pvQbATq91aObWM4TCMcoqWo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);